/// <reference types="zod-openapi" />
/**
 * Primitive value types shared by every Recueil schema.
 *
 * These mirror the notation table in `spec/data-model.md` §1.1. The database keeps the portable
 * SQLite/Postgres intersection; this module is where the shape of each of those values is actually
 * enforced, because §1.1 says so explicitly: "No length limits anywhere; length is validated by
 * Zod, not by the database".
 *
 * Naming: the database is `lower_snake_case` (§1.2), the API is `camelCase`. The mapping is
 * mechanical and lives in `packages/core`; nothing here should encode a column name.
 */
import * as z from 'zod';

/* -------------------------------------------------------------------------------------------- */
/* Identifiers                                                                                     */
/* -------------------------------------------------------------------------------------------- */

/** Crockford base32 alphabet: the digits plus the letters, less I, L, O and U. */
const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const CROCKFORD_CLASS = '[0-9A-HJKMNP-TV-Z]';

export const ULID_PATTERN = new RegExp(`^${CROCKFORD_CLASS}{26}$`);
export const PUBLIC_ID_PATTERN = new RegExp(`^${CROCKFORD_CLASS}{8}$`);

/** A surrogate primary key: a 26-character Crockford base32 ULID (`spec/data-model.md` §1.3). */
export const IdSchema = z
  .string()
  .regex(ULID_PATTERN, 'must be a 26-character Crockford base32 ULID')
  .meta({
    id: 'Id',
    title: 'Id',
    description:
      'A 26-character Crockford base32 ULID. Generated by the application, never by the database, ' +
      'and lexicographically sortable, so ordering by id is creation order.',
    examples: ['01J8F3Z9K4ABCDEFGHJKMNPQRS'],
  });

/**
 * The short public key that appears in URLs, in `recueil://item/<id>` deep links and in the
 * connector protocol: eight uppercase Crockford base32 characters, deliberately Zotero-key-shaped
 * so an imported Zotero item key can be carried across unchanged (`spec/data-model.md` §1.3).
 */
export const PublicIdSchema = z
  .string()
  .regex(PUBLIC_ID_PATTERN, 'must be an eight-character uppercase Crockford base32 key')
  .meta({
    id: 'PublicId',
    title: 'PublicId',
    description:
      'Eight uppercase Crockford base32 characters. Zotero-key-shaped, so imported Zotero item ' +
      'keys survive migration and the REST API can expose it as `key`.',
    examples: ['A1B2C3D4'],
  });

export const isCrockfordBase32 = (value: string): boolean =>
  value.length > 0 && [...value].every((character) => CROCKFORD.includes(character));

/** The SHA-256 of a document's bytes: the identity of a Document (ADR-0004, P2). */
export const Sha256Schema = z
  .string()
  .regex(/^[0-9a-f]{64}$/, 'must be 64 lowercase hexadecimal characters')
  .meta({
    id: 'Sha256',
    title: 'Sha256',
    description: 'Lowercase hexadecimal SHA-256 digest — the content-hash identity of ADR-0004.',
    examples: ['e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'],
  });

/** A 64-bit simhash over extracted text, used as the near-duplicate blocking key (CONCEPT §5.6). */
export const SimhashSchema = z
  .string()
  .regex(/^[0-9a-f]{16}$/, 'must be 16 lowercase hexadecimal characters')
  .meta({ id: 'Simhash', title: 'Simhash', description: 'A 64-bit simhash as 16 hex characters.' });

/* -------------------------------------------------------------------------------------------- */
/* Time                                                                                            */
/* -------------------------------------------------------------------------------------------- */

export const TIMESTAMP_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;

/**
 * An instant, in the one form the schema permits: ISO-8601 UTC, always `Z`, always three
 * fractional digits. Fixed width, so lexicographic order equals chronological order in SQLite
 * (`spec/data-model.md` §1.1).
 */
export const TimestampSchema = z
  .string()
  .regex(TIMESTAMP_PATTERN, 'must be an ISO-8601 UTC timestamp of the form YYYY-MM-DDTHH:MM:SS.sssZ')
  .refine((value) => !Number.isNaN(Date.parse(value)), 'must be a real calendar instant')
  .meta({
    id: 'Timestamp',
    title: 'Timestamp',
    format: 'date-time',
    description:
      'ISO-8601 UTC with exactly three fractional digits and a literal Z. Fixed width, so ' +
      'lexicographic order is chronological order.',
    examples: ['2026-08-22T09:15:00.000Z'],
  });

export const CALENDAR_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/** A complete calendar date. Only ever used where a partial date would be meaningless. */
export const CalendarDateSchema = z
  .string()
  .regex(CALENDAR_DATE_PATTERN, 'must be a complete calendar date of the form YYYY-MM-DD')
  .refine((value) => {
    const parsed = new Date(`${value}T00:00:00.000Z`);
    return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
  }, 'must be a date that exists')
  .meta({
    id: 'CalendarDate',
    title: 'CalendarDate',
    format: 'date',
    examples: ['2026-08-22'],
  });

const EDTF_PART = String.raw`\d{4}(?:-\d{2}(?:-\d{2})?)?[?~%]?`;
export const EDTF_PATTERN = new RegExp(
  `^(?:${EDTF_PART}|${EDTF_PART}/${EDTF_PART}|\\.\\./${EDTF_PART}|${EDTF_PART}/\\.\\.)$`,
);

/**
 * A bibliographic date, which is routinely partial or approximate. Never a calendar date: a
 * year-only publication date is normal (`spec/data-model.md` §1.1).
 *
 * The supported subset of EDTF level 1: a year, year-month or year-month-day, each optionally
 * qualified with `?` (uncertain), `~` (approximate) or `%` (both), and intervals of two such
 * values, with `..` for an open end.
 */
export const EdtfDateSchema = z
  .string()
  .regex(EDTF_PATTERN, 'must be an EDTF date, date-part or interval (e.g. 2019, 2019-04, 2019-04-01/2019-04-03)')
  .meta({
    id: 'EdtfDate',
    title: 'EdtfDate',
    description:
      'Extended Date/Time Format, level 1 subset: partial and approximate bibliographic dates.',
    examples: ['2019', '2019-04', '2019-04-01/2019-04-03', '1920~'],
  });

/* -------------------------------------------------------------------------------------------- */
/* Small scalars                                                                                   */
/* -------------------------------------------------------------------------------------------- */

/** A resolver's or heuristic's confidence in a derived fact (P4). */
export const ConfidenceSchema = z.number().min(0).max(1).meta({
  id: 'Confidence',
  title: 'Confidence',
  description: 'Confidence in a derived fact, from 0 (none) to 1 (certain).',
  examples: [0.92],
});

export const HexColourSchema = z
  .string()
  .regex(/^#[0-9a-fA-F]{6}$/, 'must be a six-digit hex colour of the form #rrggbb')
  .meta({ id: 'HexColour', title: 'HexColour', examples: ['#ffd400'] });

export const CurrencyCodeSchema = z
  .string()
  .regex(/^[A-Z]{3}$/, 'must be a three-letter uppercase ISO-4217 code')
  .meta({ id: 'CurrencyCode', title: 'CurrencyCode', examples: ['EUR'] });

export const CountryCodeSchema = z
  .string()
  .regex(/^[A-Z]{2}$/, 'must be a two-letter uppercase ISO-3166-1 alpha-2 code')
  .meta({ id: 'CountryCode', title: 'CountryCode', examples: ['DE'] });

export const LanguageTagSchema = z
  .string()
  .regex(/^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/, 'must be a BCP-47 language tag')
  .meta({ id: 'LanguageTag', title: 'LanguageTag', examples: ['en-GB'] });

export const UrlSchema = z
  .string()
  .max(4096)
  .refine((value) => {
    try {
      const parsed = new URL(value);
      return parsed.protocol === 'http:' || parsed.protocol === 'https:';
    } catch {
      return false;
    }
  }, 'must be an absolute http(s) URL')
  .meta({ id: 'Url', title: 'Url', format: 'uri', examples: ['https://example.org/paper.pdf'] });

/** A short free-text label. Bounded so that a runaway import cannot write a novel into a title. */
export const ShortTextSchema = z.string().min(1).max(1024);
export const LongTextSchema = z.string().max(1_000_000);

/** A non-negative count of things. */
export const CountSchema = z.number().int().min(0);

/**
 * The slug shape used for every extensible vocabulary key: custom field keys, item types, job
 * types, check ids. Lowercase, starts with a letter, no punctuation but the underscore
 * (`spec/data-model.md` §4.6, `ck_custom_fields_key_shape`).
 */
export const SLUG_PATTERN = /^[a-z][a-z0-9_]*$/;
export const SlugSchema = z
  .string()
  .min(1)
  .max(64)
  .regex(SLUG_PATTERN, 'must be a lowercase slug matching [a-z][a-z0-9_]*');

/* -------------------------------------------------------------------------------------------- */
/* JSON                                                                                            */
/* -------------------------------------------------------------------------------------------- */

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/**
 * Any JSON value. Used where the database column is `JSON` and the content is opaque to SQL.
 *
 * The recursion goes through a single stable instance rather than a fresh one per call, because a
 * lazy schema rebuilt on every access is rendered as a new anonymous component every time it is
 * reached, and the generated document ends up with a `__schema0` per JSON column.
 */
export const JsonValueSchema: z.ZodType<JsonValue> = z.lazy(() => jsonValueUnion).meta({
  id: 'JsonValue',
  title: 'JsonValue',
  description: 'Any JSON value: a string, number, boolean, null, array or object.',
});

const jsonValueUnion = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.null(),
  z.array(JsonValueSchema),
  z.record(z.string(), JsonValueSchema),
]);

/** A JSON object. The default for `JSON` columns whose default is `{}`. */
export const JsonObjectSchema = z.record(z.string(), JsonValueSchema).meta({
  id: 'JsonObject',
  title: 'JsonObject',
  description: 'An arbitrary JSON object.',
});

/* -------------------------------------------------------------------------------------------- */
/* Check digits                                                                                    */
/* -------------------------------------------------------------------------------------------- */

/** ISBN-13 check digit, alternating weights 1 and 3, modulo 10. */
export const isValidIsbn13 = (digits: string): boolean => {
  if (!/^\d{13}$/.test(digits)) return false;
  let sum = 0;
  for (let index = 0; index < 13; index += 1) {
    sum += Number(digits[index]) * (index % 2 === 0 ? 1 : 3);
  }
  return sum % 10 === 0;
};

/** ISSN check digit, weights 8..2, modulo 11, with X for 10. */
export const isValidIssn = (value: string): boolean => {
  if (!/^\d{4}-\d{3}[\dX]$/.test(value)) return false;
  const digits = value.replace('-', '');
  let sum = 0;
  for (let index = 0; index < 7; index += 1) {
    sum += Number(digits[index]) * (8 - index);
  }
  const remainder = (11 - (sum % 11)) % 11;
  const expected = remainder === 10 ? 'X' : String(remainder);
  return digits[7] === expected;
};

/** ORCID check digit: ISO 7064 MOD 11-2 over the 15 leading digits. */
export const isValidOrcid = (value: string): boolean => {
  if (!/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/.test(value)) return false;
  const digits = value.replace(/-/g, '');
  let total = 0;
  for (let index = 0; index < 15; index += 1) {
    total = (total + Number(digits[index])) * 2;
  }
  const remainder = total % 11;
  const result = (12 - remainder) % 11;
  const expected = result === 10 ? 'X' : String(result);
  return digits[15] === expected;
};
