/**
 * Identifier generation.
 *
 * `spec/data-model.md` §1.3 fixes two identifier shapes and both are generated by the application,
 * never by the database, so that a record can be constructed and referenced inside one transaction
 * and so that ids survive an export/import round trip:
 *
 * - the surrogate primary key is a 26-character Crockford base32 ULID, which makes `ORDER BY id`
 *   creation order and gives the audit log and the job log a total order for free;
 * - entities that appear in URLs, citation keys or the connector protocol additionally carry an
 *   eight-character uppercase Crockford base32 `public_id`, deliberately Zotero-key-shaped.
 *
 * Both shapes are validated by `@recueil/schemas` (`IdSchema`, `PublicIdSchema`); this module is
 * the only place that mints them.
 */
import { randomInt } from 'node:crypto';

import { ulid } from 'ulid';

/** Crockford base32: the digits and the letters, less I, L, O and U. */
const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

/** A new surrogate primary key. Monotonic within a millisecond is not required, sortable is. */
export const newId = (): string => ulid();

/** A new eight-character public key (§1.3). */
export const newPublicId = (): string => {
  let out = '';
  for (let index = 0; index < 8; index += 1) out += CROCKFORD[randomInt(CROCKFORD.length)];
  return out;
};
