--
-- Generated by drizzle-kit from the `ck_trash_merge` change in `schema.ts`, and kept because
-- widening a `CHECK` in SQLite is a table rebuild rather than an `ALTER`.
--
-- What changes and why. The check was `reason <> 'merge' OR merge_target_item_id IS NOT NULL`,
-- straight from `spec/data-model.md` §6.6. That reading assumes every merge is an item merge, but
-- two other invariants also merge: TG2 says merging two tags "is a merge like any other and leaves
-- a reversible record in `trash`", and CR1 says a creator merge puts the previous ids in the merge
-- record. Neither winner is an item, so neither can populate a foreign key to `items`, and the old
-- check made `reason = 'merge'` unusable for them -- which would have forced tag and creator merges
-- to be recorded as ordinary user deletions, losing the one word that says what happened.
--
-- So the rule is scoped to the entity it was written for: an **item** merge must still name its
-- winning item, and a tag or creator merge records its winner in `merge_record`.
--
-- `PRAGMA foreign_keys` is a no-op inside a transaction, which is where the migrator runs this.
-- That is harmless here: `trash` has outgoing foreign keys only -- nothing references it -- so
-- copying rows that were already valid cannot violate one.
--
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_trash` (
	`id` text PRIMARY KEY NOT NULL,
	`entity_type` text NOT NULL,
	`entity_id` text NOT NULL,
	`group_id` text,
	`trashed_at` text NOT NULL,
	`trashed_by_user_id` text,
	`reason` text DEFAULT 'user' NOT NULL,
	`reason_detail` text,
	`restore_payload` text DEFAULT '{}' NOT NULL,
	`merge_target_item_id` text,
	`merge_record` text,
	`expires_at` text,
	`restored_at` text,
	`restored_by_user_id` text,
	`purged_at` text,
	`purged_by_user_id` text,
	FOREIGN KEY (`trashed_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`merge_target_item_id`) REFERENCES `items`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`restored_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`purged_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "ck_trash_entity_type" CHECK("entity_type" in ('item', 'document', 'attachment', 'collection', 'note', 'annotation', 'tag', 'creator', 'review', 'curated_network')),
	CONSTRAINT "ck_trash_reason" CHECK("reason" in ('user', 'merge', 'import_rollback', 'cascade', 'plugin')),
	CONSTRAINT "ck_trash_merge" CHECK("reason" <> 'merge'
        or "merge_target_item_id" is not null
        or "entity_type" <> 'item'),
	CONSTRAINT "ck_trash_restore_payload_json" CHECK(json_valid("restore_payload")),
	CONSTRAINT "ck_trash_merge_record_json" CHECK("merge_record" is null or json_valid("merge_record"))
);
--> statement-breakpoint
INSERT INTO `__new_trash`("id", "entity_type", "entity_id", "group_id", "trashed_at", "trashed_by_user_id", "reason", "reason_detail", "restore_payload", "merge_target_item_id", "merge_record", "expires_at", "restored_at", "restored_by_user_id", "purged_at", "purged_by_user_id") SELECT "id", "entity_type", "entity_id", "group_id", "trashed_at", "trashed_by_user_id", "reason", "reason_detail", "restore_payload", "merge_target_item_id", "merge_record", "expires_at", "restored_at", "restored_by_user_id", "purged_at", "purged_by_user_id" FROM `trash`;--> statement-breakpoint
DROP TABLE `trash`;--> statement-breakpoint
ALTER TABLE `__new_trash` RENAME TO `trash`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `ux_trash_open` ON `trash` (`entity_type`,`entity_id`) WHERE restored_at is null and purged_at is null;--> statement-breakpoint
CREATE INDEX `ix_trash_open` ON `trash` (`trashed_at`) WHERE restored_at is null and purged_at is null;--> statement-breakpoint
CREATE INDEX `ix_trash_group` ON `trash` (`group_id`) WHERE group_id is not null;--> statement-breakpoint
CREATE INDEX `ix_trash_merge_target` ON `trash` (`merge_target_item_id`) WHERE merge_target_item_id is not null;--> statement-breakpoint
CREATE INDEX `ix_trash_expires` ON `trash` (`expires_at`) WHERE expires_at is not null and purged_at is null;