/**
 * Which citation key an imported item keeps (ADR-0016, CONCEPT §6).
 *
 * A citation key is the one identifier that has already left the library: it is in every
 * `\cite{}` of every manuscript the user has written. ADR-0016 is therefore unambiguous about
 * migration — "Keys arriving from migration — Zotero 8 native keys, Better BibTeX keys from
 * `better-bibtex.sqlite` or from an `Extra` line — are imported **pinned**, so migration cannot
 * rewrite a key that is already in a manuscript." Everything here serves that sentence.
 *
 * A real library can carry the same item's key in three places at once, disagreeing. The
 * precedence is by how deliberate each source is:
 *
 * 1. **Zotero 8's native `citationKey` field.** The newest mechanism and an explicit user action.
 * 2. **A `Citation Key:` line in `Extra`.** Better BibTeX's own way of pinning, and equally
 *    deliberate; it predates the native field, so it loses to it.
 * 3. **A pinned row in `better-bibtex.sqlite`.** Deliberate, but held outside the library.
 * 4. **An unpinned row in `better-bibtex.sqlite`.** Generated by the plugin — and still the key
 *    that Better BibTeX exported into the `.bib` the manuscripts were built from, which is why it
 *    is imported, and imported pinned, rather than regenerated.
 *
 * Every disagreement is recorded, with all the candidates, so the report can show it rather than
 * the importer having to guess correctly.
 */

export type CitationKeySource = 'zotero_native' | 'extra_line' | 'better_bibtex_pinned' | 'better_bibtex';

export interface CitationKeyCandidate {
  source: CitationKeySource;
  key: string;
}

export interface ResolvedCitationKey {
  key: string | null;
  source: CitationKeySource | null;
  /**
   * Always true for a key that came from Zotero: ADR-0016 imports migrated keys pinned. Present as
   * a field rather than assumed, so the rule is visible at the call site.
   */
  pinned: boolean;
  /** Every candidate found, in precedence order. Length > 1 means the sources disagree. */
  candidates: CitationKeyCandidate[];
  /** True when two or more candidates carry different keys. */
  conflict: boolean;
}

export interface CitationKeyInputs {
  /** Zotero 8's `citationKey` field. */
  native?: string | null;
  /** The `Citation Key:` line of `Extra`. */
  extraLine?: string | null;
  /** The key from `better-bibtex.sqlite`, with its pin flag. */
  betterBibtex?: { key: string; pinned: boolean } | null;
}

/** Resolve one item's key. */
export const resolveCitationKey = (inputs: CitationKeyInputs): ResolvedCitationKey => {
  const candidates: CitationKeyCandidate[] = [];

  const push = (source: CitationKeySource, value: string | null | undefined): void => {
    const key = (value ?? '').trim();
    if (key !== '') candidates.push({ source, key });
  };

  push('zotero_native', inputs.native);
  push('extra_line', inputs.extraLine);
  if (inputs.betterBibtex != null) {
    push(inputs.betterBibtex.pinned ? 'better_bibtex_pinned' : 'better_bibtex', inputs.betterBibtex.key);
  }

  const winner = candidates[0];
  const distinct = new Set(candidates.map((candidate) => candidate.key));

  return {
    key: winner?.key ?? null,
    source: winner?.source ?? null,
    pinned: winner !== undefined,
    candidates,
    conflict: distinct.size > 1,
  };
};
